local function CreateHeaderLabel(text, parent)
    local label = vgui.Create("DLabel", parent)
    label:SetText(text)
    label:SetContentAlignment(5)
    label:SetTall(30)
    label:Dock(TOP)
    label:DockMargin(15, 15, 15, 15)
    label:SetFont("CloseCaption_Bold")
    label:SetTextColor(Color(255, 255, 255))

    label.Paint = function(self, w, h)
        local bgColor = self:IsHovered() and Color(80, 80, 80, 255) or Color(50, 50, 50, 255)
        draw.RoundedBox(4, 0, 0, w, h, bgColor)
    end

    return label
end

local function CreateButton(text, parent, command)
    local button = vgui.Create("DButton", parent)
    button:SetText(text)
    button:SetTall(40)
    button:Dock(TOP)
    button:DockMargin(5, 10, 5, 5)
    button:SetFont("CloseCaption_Bold")
    button:SetTextColor(Color(255, 255, 255))

    button.Paint = function(self, w, h)
        local bgColor = self:IsHovered() and Color(80, 80, 80, 255) or Color(50, 50, 50, 255)
        draw.RoundedBox(4, 0, 0, w, h, bgColor)
    end

    button.DoClick = function()
        RunConsoleCommand(command)
    end

    return button
end

hook.Add("PopulateToolMenu", "BattleBeats_Settings", function()
    spawnmenu.AddToolMenuOption("Utilities", "BattleBeats", "BattleBeatsMenu", "General", "", "", function(panel)
        panel:ClearControls()
        CreateHeaderLabel("GENERAL", panel)
        panel:CheckBox("#btb.spawnmenu.general.enable_ambient", "battlebeats_enable_ambient")
        panel:CheckBox("#btb.spawnmenu.general.enable_combat", "battlebeats_enable_combat")
        panel:CheckBox("#btb.spawnmenu.general.force_combat", "battlebeats_force_combat")
        panel:Help("#btb.spawnmenu.general.force_combat_tip")
        panel:CheckBox("#btb.spawnmenu.general.npc_combat", "battlebeats_npc_combat")
        panel:Help("#btb.spawnmenu.general.npc_combat_tip")
        local combo = panel:ComboBox("#btb.spawnmenu.general.combo", "battlebeats_disable_mode")
        combo:AddChoice("#btb.spawnmenu.general.combo_1", 0)
        combo:AddChoice("#btb.spawnmenu.general.combo_2", 1)
        combo:AddChoice("#btb.spawnmenu.general.combo_3", 2)
        panel:Help("#btb.spawnmenu.general.combo_tip")
        panel:CheckBox("#btb.spawnmenu.general.enable_assigned", "battlebeats_enable_assigned_tracks")
        panel:Help("#btb.spawnmenu.general.enable_assigned_tip")
        panel:NumSlider("#btb.spawnmenu.general.master_volume", "battlebeats_volume", 0, 200, 0)
        panel:ControlHelp("#btb.spawnmenu.general.master_volume_tip")
        panel:NumSlider("#btb.spawnmenu.general.ambient_volume", "battlebeats_volume_ambient", 0, 100, 0)
        panel:NumSlider("#btb.spawnmenu.general.combat_volume", "battlebeats_volume_combat", 0, 100, 0)
        panel:Help("")
        CreateButton("#btb.spawnmenu.general.btb_packs", panel, "battlebeats_menu")
        panel:ControlHelp("#btb.spawnmenu.general.btb_packs_tip")
        CreateButton("#btb.spawnmenu.general.next_track", panel, "battlebeats_force_next_track")
        panel:Help("")
        panel:Help("")
        CreateButton("#btb.spawnmenu.general.options_panel", panel, "battlebeats_options")
        panel:Help("#btb.spawnmenu.general.options_panel_tip")
    end)
    spawnmenu.AddToolMenuOption("Utilities", "BattleBeats", "BattleBeatsServer", "Server", "", "", function(panel)
        panel:ClearControls()
        if LocalPlayer():IsAdmin() then
            CreateHeaderLabel("SERVER", panel)
            panel:NumSlider("#btb.spawnmenu.server.combat_cooldown", "battlebeats_server_combat_cooldown", 3, 30, 0)
            panel:Help("#btb.spawnmenu.server.combat_cooldown_tip")
            CreateHeaderLabel("PVE", panel)
            panel:NumSlider("#btb.spawnmenu.server.trigger_distance", "battlebeats_server_max_distance", 100, 10000, 0)
            panel:Help("#btb.spawnmenu.server.trigger_distance_tip")
            CreateHeaderLabel("PVP", panel)
            panel:CheckBox("#btb.spawnmenu.server.enable_pvp", "battlebeats_pvp_enable")
            panel:CheckBox("#btb.spawnmenu.server.enable_pvp_teammates", "battlebeats_pvp_allow_team_combat")
            panel:CheckBox("#btb.spawnmenu.server.enable_pvp_los", "battlebeats_pvp_lineofsight")
            panel:Help("#btb.spawnmenu.server.enable_pvp_los_tip")
            local combo = panel:ComboBox("#btb.spawnmenu.server.combo", "battlebeats_pvp_mode")
            combo:AddChoice("#btb.spawnmenu.server.combo_1", 0)
            combo:AddChoice("#btb.spawnmenu.server.combo_2", 1)
            combo:AddChoice("#btb.spawnmenu.server.combo_3", 2)
            panel:Help("#btb.spawnmenu.server.combo_1_tip")
            panel:Help("#btb.spawnmenu.server.combo_2_tip")
            panel:Help("#btb.spawnmenu.server.combo_3_tip")
            panel:NumSlider("#btb.spawnmenu.server.combat_time", "battlebeats_pvp_combat_time", 5, 120, 0)
            panel:Help("#btb.spawnmenu.server.combat_time_tip")
            panel:NumSlider("#btb.spawnmenu.server.visibility", "battlebeats_pvp_max_distance", 100, 10000, 0)
            panel:Help("#btb.spawnmenu.server.visibility_tip")
        end
    end)
end)