local function CreateHeaderLabel(text, parent)
    local label = vgui.Create("DLabel", parent)
    label:SetText(text)
    label:SetContentAlignment(5)
    label:SetTall(30)
    label:Dock(TOP)
    label:DockMargin(15, 15, 15, 15)
    label:SetFont("CloseCaption_Bold")
    label:SetTextColor(Color(255, 255, 255))

    label.Paint = function(self, w, h)
        local bgColor = self:IsHovered() and Color(80, 80, 80, 255) or Color(50, 50, 50, 255)
        draw.RoundedBox(4, 0, 0, w, h, bgColor)
    end

    return label
end

local function CreateButton(text, parent, command)
    local button = vgui.Create("DButton", parent)
    button:SetText(text)
    button:SetTall(40)
    button:Dock(TOP)
    button:DockMargin(5, 10, 5, 5)
    button:SetFont("CloseCaption_Bold")
    button:SetTextColor(Color(255, 255, 255))

    button.Paint = function(self, w, h)
        local bgColor = self:IsHovered() and Color(80, 80, 80, 255) or Color(50, 50, 50, 255)
        draw.RoundedBox(4, 0, 0, w, h, bgColor)
    end

    button.DoClick = function()
        RunConsoleCommand(command)
    end

    return button
end

hook.Add("PopulateToolMenu", "BattleBeats_Settings", function()
    spawnmenu.AddToolMenuOption("Utilities", "BattleBeats", "BattleBeatsMenu", "General", "", "", function(panel)
        panel:ClearControls()
        CreateHeaderLabel("GENERAL", panel)
        panel:CheckBox("Enable ambient music ", "battlebeats_enable_ambient")
        panel:CheckBox("Enable combat music ", "battlebeats_enable_combat")
        panel:CheckBox("Force combat ", "battlebeats_force_combat")
        panel:Help("Forces combat music to play regardless of nearby hostile NPCs. This won't work if combat music is disabled")
        panel:CheckBox("NPC's fight triggers combat ", "battlebeats_npc_combat")
        panel:Help("Triggers combat when an NPC is targeting other NPCs or players")
        local combo = panel:ComboBox("On death behavior", "battlebeats_disable_mode")
        combo:AddChoice("Nothing", 0)
        combo:AddChoice("Mute completely", 1)
        combo:AddChoice("Lower volume", 2)
        panel:Help("Select what should happen to music when you die")
        panel:CheckBox("Enable assigned tracks", "battlebeats_enable_assigned_tracks")
        panel:Help("Plays assigned tracks when their NPCs are present")
        panel:NumSlider("Master Volume (%)", "battlebeats_volume", 0, 200, 0)
        panel:ControlHelp("Tip: You can go over 200 up to 1000 using console command 'battlebeats_volume'")
        panel:NumSlider("Ambient Volume (%)", "battlebeats_volume_ambient", 0, 100, 0)
        panel:NumSlider("Combat Volume (%)", "battlebeats_volume_combat", 0, 100, 0)
        panel:Help("")
        CreateButton("BattleBeats Packs", panel, "battlebeats_menu")
        panel:ControlHelp("Tip: The console command to open the menu is 'battlebeats_menu'")
        CreateButton("Force Next Track", panel, "battlebeats_force_next_track")
        panel:Help("")
        panel:Help("")
        CreateButton("Open Options Panel", panel, "battlebeats_options")
        panel:Help("Opens full version of client options for battlebeats")
    end)
    spawnmenu.AddToolMenuOption("Utilities", "BattleBeats", "BattleBeatsServer", "Server", "", "", function(panel)
        panel:ClearControls()
        if LocalPlayer():IsAdmin() then
            CreateHeaderLabel("SERVER", panel)
            panel:NumSlider("Combat cooldown", "battlebeats_server_combat_cooldown", 3, 30, 0)
            panel:Help("Defines how long the player remains in combat after actual combat ends")
            CreateHeaderLabel("PVE", panel)
            panel:NumSlider("Trigger distance", "battlebeats_server_max_distance", 100, 10000, 0)
            panel:Help("Maximum distance between the player and an NPC to trigger combat")
            panel:Help("In theory, a lower number means better performance, but the difference is negligible")
            CreateHeaderLabel("PVP", panel)
            panel:CheckBox("Enable PVP ", "battlebeats_pvp_enable")
            panel:CheckBox("Allow PVP between teammates ", "battlebeats_pvp_allow_team_combat")
            panel:CheckBox("PVP requires LoS ", "battlebeats_pvp_lineofsight")
            panel:Help("LoS - Line of Sight. If enabled, combat will only trigger when you have visual contact with an enemy")
            local combo = panel:ComboBox("PVP Mode", "battlebeats_pvp_mode")
            combo:AddChoice("Damage-Based: Until death", 0)
            combo:AddChoice("Damage-Based: Timeout", 1)
            combo:AddChoice("Visibility-Based: Enemy Visible", 2)
            panel:Help("Damage-Based: Until death - After dealing damage to a player, both stay in combat until one dies")
            panel:Help("Damage-Based: Timeout - After dealing damage, combat state lasts until the combat time expires (resets on each hit)")
            panel:Help("Visibility-Based: Enemy Visible - Combat starts when an enemy from another team is nearby or visible, depending on your settings")
            panel:NumSlider("Combat time ", "battlebeats_pvp_combat_time", 5, 120, 0)
            panel:Help("The amount of time before combat ends if no further damage is dealt in timeout mode")
            panel:NumSlider("Visibility distance ", "battlebeats_pvp_max_distance", 100, 10000, 0)
            panel:Help("Maximum distance between you and an enemy required to trigger combat in visibility mode")
        end
    end)
end)