local function CreateHeaderLabel(text, parent)
    local label = vgui.Create("DLabel", parent)
    label:SetText(text)
    label:SetContentAlignment(5)
    label:SetTall(30)
    label:Dock(TOP)
    label:DockMargin(15, 15, 15, 15)
    label:SetFont("CloseCaption_Bold")
    label:SetTextColor(Color(255, 255, 255))

    label.Paint = function(self, w, h)
        local bgColor = self:IsHovered() and Color(80, 80, 80, 255) or Color(50, 50, 50, 255)
        draw.RoundedBox(4, 0, 0, w, h, bgColor)
    end

    return label
end

local function CreateButton(text, parent, command)
    local button = vgui.Create("DButton", parent)
    button:SetText(text)
    button:SetTall(40)
    button:Dock(TOP)
    button:DockMargin(5, 10, 5, 5)
    button:SetFont("CloseCaption_Bold")
    button:SetTextColor(Color(255, 255, 255))

    button.Paint = function(self, w, h)
        local bgColor = self:IsHovered() and Color(80, 80, 80, 255) or Color(50, 50, 50, 255)
        draw.RoundedBox(4, 0, 0, w, h, bgColor)
    end

    button.DoClick = function()
        RunConsoleCommand(command)
    end

    return button
end

hook.Add("PopulateToolMenu", "BattleBeats_Settings", function()
    spawnmenu.AddToolMenuOption("Utilities", "BattleBeats", "BattleBeatsMenu", "General", "", "", function(panel)
        panel:ClearControls()
        CreateHeaderLabel("GENERAL", panel)
        panel:CheckBox("Enable ambient music ", "battlebeats_enable_ambient")
        panel:CheckBox("Enable combat music ", "battlebeats_enable_combat")
        panel:CheckBox("Force combat ", "battlebeats_force_combat")
        panel:Help("Forces combat music to play regardless of nearby hostile NPCs. This won't work if combat music is disabled")
        panel:CheckBox("NPC's fight triggers combat ", "battlebeats_npc_combat")
        panel:Help("Triggers combat when an NPC is targeting other NPCs or players")
        local combo = panel:ComboBox("On death behavior", "battlebeats_disable_mode")
        combo:AddChoice("Nothing", 0)
        combo:AddChoice("Mute completely", 1)
        combo:AddChoice("Lower volume", 2)
        panel:Help("Select what should happen to music when you die")
        panel:CheckBox("Enable assigned tracks", "battlebeats_enable_assigned_tracks")
        panel:Help("Plays assigned tracks when their NPCs are present")
        panel:NumSlider("Master Volume (%)", "battlebeats_volume", 0, 200, 0)
        panel:ControlHelp("Tip: You can go over 200 up to 1000 using console command 'battlebeats_volume'")
        panel:NumSlider("Ambient Volume (%)", "battlebeats_volume_ambient", 0, 100, 0)
        panel:NumSlider("Combat Volume (%)", "battlebeats_volume_combat", 0, 100, 0)
        panel:Help("")
        CreateButton("BattleBeats Packs", panel, "battlebeats_menu")
        panel:ControlHelp("Tip: The console command to open the menu is 'battlebeats_menu'")
        CreateButton("Force Next Track", panel, "battlebeats_force_next_track")
        panel:Help("")
        panel:Help("")
        CreateButton("Open Options Panel", panel, "battlebeats_options")
        panel:Help("Opens fancier version of client options for battlebeats")
    end)
    spawnmenu.AddToolMenuOption("Utilities", "BattleBeats", "BattleBeatsMMenu", "Notification", "", "", function(panel)
        panel:ClearControls()
        CreateHeaderLabel("NOTIFICATIONS", panel)
        panel:CheckBox("Enable notification ", "battlebeats_show_notification")
        panel:CheckBox("Notification always visible ", "battlebeats_persistent_notification")
        panel:Help("The notification will remain visible for the entire duration of the music, instead of disappearing after a few seconds")
        panel:CheckBox("Show progress bar ", "battlebeats_show_status_bar")
        panel:Help("Displays a progress bar for the current track (showing total time and current time) at the bottom of the notification")
        panel:CheckBox("Show replay notification ", "battlebeats_show_notification_after_continue")
        panel:Help("Displays a notification even if the same track is replayed (e.g. after leaving combat before the wait time ends). (This is enabled by default if 'Notification always ON' is active)")
        panel:CheckBox("Skip Nombat track names ", "battlebeats_skip_nombat_names")
        panel:Help("Hides track names like C7 or A2 when playing tracks from Nombat packs")
        panel:CheckBox("Enable preview notification ", "battlebeats_show_preview_notification")
        panel:Help("Shows notification when you are previewing tracks")
        panel:CheckBox("Show pack name in notification", "battlebeats_show_notification_pack_name")
        panel:Help("Shows the pack name of the currently played track in the notification")
        panel:CheckBox("Show notification visualizer ", "battlebeats_show_notification_visualizer")
        panel:Help("Show FFT bars in the track notification")
        panel:CheckBox("Visualizer amplitude smoothing ", "battlebeats_visualizer_smooth")
        panel:Help("Enable amplitude smoothing for the visualizer")
        panel:NumSlider("Visualizer Boost", "battlebeats_visualizer_boost", 1, 20, 0)
        panel:Help("Multiplier for visualizer amplitude boost (used in log scale)")
        panel:Help("")
        panel:NumSlider("Notification X position", "battlebeats_notif_x", 0, ScrW(), 0)
        panel:NumSlider("Notification Y position", "battlebeats_notif_y", 0, ScrH(), 0)
        panel:Help("While changing position, a box showing the previewed position will appear")
        panel:Help("")
        panel:Help("Font color meaning:\n- Green: Ambient track is playing\n- Orange: Combat track is playing\n- Yellow: Previewed track is playing from the previewer (cannot switch to ambient or combat during this)")
    end)
    spawnmenu.AddToolMenuOption("Utilities", "BattleBeats", "BattleBeatsServer", "Server", "", "", function(panel)
        panel:ClearControls()
        if LocalPlayer():IsAdmin() then
            CreateHeaderLabel("SERVER", panel)
            panel:NumSlider("Combat cooldown", "battlebeats_server_combat_cooldown", 3, 30, 0)
            panel:Help("Defines how long the player remains in combat after actual combat ends")
            CreateHeaderLabel("PVE", panel)
            panel:NumSlider("Trigger distance", "battlebeats_server_max_distance", 100, 10000, 0)
            panel:Help("Maximum distance between the player and an NPC to trigger combat")
            panel:Help("In theory, a lower number means better performance, but the difference is negligible")
            CreateHeaderLabel("PVP", panel)
            panel:CheckBox("Enable PVP ", "battlebeats_pvp_enable")
            panel:CheckBox("Allow PVP between teammates ", "battlebeats_pvp_allow_team_combat")
            panel:CheckBox("PVP requires LoS ", "battlebeats_pvp_lineofsight")
            panel:Help("LoS - Line of Sight. If enabled, combat will only trigger when you have visual contact with an enemy")
            local combo = panel:ComboBox("PVP Mode", "battlebeats_pvp_mode")
            combo:AddChoice("Damage-Based: Until death", 0)
            combo:AddChoice("Damage-Based: Timeout", 1)
            combo:AddChoice("Visibility-Based: Enemy Visible", 2)
            panel:Help("Damage-Based: Until death - After dealing damage to a player, both stay in combat until one dies")
            panel:Help("Damage-Based: Timeout - After dealing damage, combat state lasts until the combat time expires (resets on each hit)")
            panel:Help("Visibility-Based: Enemy Visible - Combat starts when an enemy from another team is nearby or visible, depending on your settings")
            panel:NumSlider("Combat time ", "battlebeats_pvp_combat_time", 5, 120, 0)
            panel:Help("The amount of time before combat ends if no further damage is dealt in timeout mode")
            panel:NumSlider("Visibility distance ", "battlebeats_pvp_max_distance", 100, 10000, 0)
            panel:Help("Maximum distance between you and an enemy required to trigger combat in visibility mode")
        end
    end)
    spawnmenu.AddToolMenuOption("Utilities", "BattleBeats", "BattleBeatsMMMenu", "Advanced", "", "", function(panel)
        panel:ClearControls()
        CreateHeaderLabel("MUSIC PLAYER", panel)
        panel:CheckBox("Switch to current pack only ", "battlebeats_exclusive_play")
        panel:Help("When switching between ambient and combat, only tracks from the same pack will be used. When a track ends naturally, the next one will still be chosen randomly from all enabled packs")
        local combo = panel:ComboBox("Continue Mode", "battlebeats_continue_mode")
        combo:AddChoice("Resume from last position", 0)
        combo:AddChoice("Play simultaneously", 1)
        panel:Help("Resume from last position: the track will continue from where it left off before switching.\nPlay simultaneously: tracks continue playing in the background during switches. For example, if you enter combat after 1 minute of ambient, then return 30 seconds later, ambient will resume from 1:30")
        panel:NumSlider("Ambient wait time ", "battlebeats_ambient_wait_time", 1, 120, 0)
        panel:NumSlider("Combat wait time ", "battlebeats_combat_wait_time", 1, 120, 0)
        panel:Help("Wait time defines how long the music player will wait before replacing the previous track with a new one. For example, if the ambient wait time is set to 20, and you enter and end combat in less than 20 seconds, the previously playing track will keep playing")
        panel:CheckBox("Always continue previous track ", "battlebeats_always_continue")
        panel:Help("Skips the wait time and always resumes the previous track until it finishes playing")
        panel:CheckBox("Lower volume in menu ", "battlebeats_lower_volume_in_menu")
        panel:Help("Lowers volume in game/spawn menu ('escape' menu won't work in singleplayer - timers pause when menu is open)")
        CreateHeaderLabel("ASSIGNED TRACKS", panel)
        panel:CheckBox("Exclude assigned tracks", "battlebeats_exclude_mapped_tracks")
        panel:Help("Tracks assigned to NPCs will not play when selecting random combat tracks")
        panel:CheckBox("Switch to lower priority", "battlebeats_switch_on_lower_priority")
        panel:Help("A track with higher priority will switch to a lower priority (if available) when the NPC with that priority dies")
        CreateHeaderLabel("SUBTITLES", panel)
        panel:CheckBox("Enable subtitles ", "battlebeats_subtitles_enabled")
        CreateHeaderLabel("MISC", panel)
        panel:CheckBox("NPC Combat requires LoS ", "battlebeats_detection_mode")
        panel:Help("LoS - Line of Sight. If enabled, combat will only trigger when you have visual contact with an enemy")
        panel:CheckBox("Auto Popup ", "battlebeats_autopopup")
        panel:Help("Automatically open the BattleBeats pack selector on startup if no packs are selected")
        panel:CheckBox("Load local packs ", "battlebeats_load_local_packs")
        panel:Help("Enables loading music packs directly from the addons/ folder without needing to upload them to Workshop. This will not work if Debug Mode is enabled (Not intended for testing sound packs - use debug mode for that instead) (Requires restart or packs reload)")
        panel:CheckBox("Debug ", "battlebeats_debug_mode")
        panel:Help("Used for testing sound packs and debugging functions. Some features may be disabled while debug mode is active (Requires restart or packs reload)")
        panel:Help("")
        CreateButton("Reload Packs", panel, "battlebeats_reload_packs")
    end)
end)